# Generated by Django 5.0.4 on 2024-04-20 18:50

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='images',
            field=models.FileField(upload_to=home.models.upload_path_carousel, verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=250, verbose_name='Tên Sản Phẩm'),
        ),
    ]
