# Generated by Django 5.0.4 on 2024-04-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_carouselimage_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(blank=True, verbose_name='Giá Cũ'),
        ),
    ]
